src/app/__init__.py
from app.views import views
from app.cache import cache
from flask import Flask
import requests

app = Flask(__name__, static_folder="public")
cache.init_app(app)

with open("version") as version:
    version = version.read()

web_version = requests.get("https://raw.githubusercontent.com/MediahTM/Mediah-Local/main/src/version").text

if float(version) >= float(web_version):
    app.register_blueprint(views)
else:
    print("Please update your version of Mediah-Local\nVisit 'https://github.com/MediahTM/Mediah-Local' and follow the install instructions")
    exit()

src/app/views.py
from flask import Blueprint, render_template, request, jsonify
from app.cache import cache
import requests

views = Blueprint("views", __name__)

@views.context_processor
def globals():
    return {
        "tmdb_apikey": "bfe60268dcb9f6352a6ff6ce40312265" # This can be left public!
    }

def cache_key():
    return request.url

@views.route("/")
def index():
    return render_template("pages/index.html")

@views.route("/view")
def view():
    return render_template("pages/view.html")

@views.route("/search")
def search():
    return render_template("pages/search.html")

@views.route("/api/json")
@cache.cached(timeout=1000, key_prefix=cache_key)
def get_json():
    url = request.args.get("url")
    response = requests.get(url)
    if response.status_code in [200, 201]:
        return jsonify(response.json()), 200
    else:
        return jsonify({"error": "Could not resolve the JSON!"}), 409

src/app/templates/index.html
{% extends "layout.html" %}

{% block content %}
    <div class="px-4">
        <div class="mx-auto container w-full space-y-6">
            {% include "parts/LatestMovies.html" %}
            {% include "parts/LatestAlbums.html" %}
        </div>
    </div>
{% endblock %}

src/app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
    <link id="favicon" rel="shortcut icon" href="{{ url_for('static', filename='favicon.png') }}" type="image/x-icon">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">

    <script src="{{ url_for('static', filename='js/filesize.min.js') }}"></script>
    <script>console.clear();console.info("Mediah Local Initialized...")</script>

    <style>*{font-family: "Inter", sans-serif;color-scheme: dark !important;}</style>

    <title>Mediah Local</title>
</head>
<body class="bg-zinc-900 text-white pb-12">
    {% include "nav.html" %}
    {% block content %}{% endblock %}
</body>
</html>

src/app/templates/nav.html
<div class="border-b border-zinc-800 px-4">
    <div class="h-14 flex items-center justify-between container mx-auto">
        <div>
            <a href="{{ url_for('views.index') }}" class="flex select-none items-center gap-3">
                <img src="{{ url_for('static', filename='favicon.png') }}" class="w-[30px] rounded-md" alt="Mediah Logo">
                <h1 class="text-lg">Mediah Local</h1>
            </a>
        </div>
        <div class="flex items-center justify-end gap-4">
            <div class="flex items-center sm:w-64 w-4/6">
                <form action="{{ url_for('views.search') }}" id="SearchForm" class="relative w-full">
                    <input required type="text" placeholder="Search Mediah..." name="query" class="px-2 w-full py-2 pr-7 h-8 focus:ring focus:ring-zinc-600/50 bg-transparent outline-none border border-zinc-700 text-sm rounded-md">
                    <button class="w-4 mr-2 text-zinc-400 pointer-events-none h-4 absolute right-0 top-0 bottom-0 my-auto" type="submit">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="w-4 h-4"><circle cx="11" cy="11" r="8"/><path d="m21 21-4.3-4.3"/></svg>
                    </button>
                </form>
            </div>
            <div class="sm:flex hidden items-center gap-4">
                <a href="https://github.com/MediahTM" target="_blank" title="Found a bug? create us an issue!">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="hover:scale-110 w-5 h-5 transition-all"><path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4"/><path d="M9 18c-4.51 2-5-2-7-2"/></svg>
                </a>
                <a href="https://github.com/MediahTM/Mediah-Downloads/" target="_blank" title="View the entire json db we have on GitHub">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="hover:scale-110 w-5 h-5 transition-all"><path d="M4 14.899A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 2.5 8.242"/><path d="M12 12v9"/><path d="m8 17 4 4 4-4"/></svg>
                </a>
            </div>
        </div>
    </div>
</div>

src/app/templates/pages/index.html
{% extends "layout.html" %}

{% block content %}
    <div class="px-4">
        <div class="mx-auto container w-full space-y-8">
            {% include "parts/LatestFilms.html" %}
            {% include "parts/LatestAlbums.html" %}
            {% include "parts/LatestSingles.html" %}
        </div>
    </div>
{% endblock %}

src/app/templates/pages/search.html
{% extends "layout.html" %}

{% block content %}
    <div class="px-4">
        <div class="mx-auto container w-full space-y-8">
            {% include "parts/SearchMedia.html" %}
        </div>
    </div>
{% endblock %}

src/app/templates/pages/view.html
{% extends "layout.html" %}

{% block content %}
    <div class="px-4">
        <div class="mx-auto container w-full">
            <div id="FileDetailsContainer" class="my-12 h-full">
                {% include "parts/LoadingSpinner.html" %}
            </div>
        </div>
        <script>
            const FileDetailsContainer = $("#FileDetailsContainer"); 
            const url = location.search.split("?url=")[1].split("&")[0];
            const type = location.search.split("&type=")[1].split("&")[0];
            const base_url = "https://raw.githubusercontent.com/MediahTM/Mediah-Downloads/main/downloads/";
            const title_prefix = "Mediah Local"

            function formatTime(minutes) {
                if (typeof minutes !== 'number' || isNaN(minutes)) {
                    return "Invalid input, create a GitHub issue!";
                }
                const hours = Math.floor(minutes / 60) + "h";
                var remainingMinutes = minutes % 60 + "m";
                return `${hours} ${remainingMinutes}`;
            }

            console.log(`Type: ${type}`)
            
            switch(type) {
                case "film": {
                    $.get({
                        url: `${base_url}${url}`,
                        success: (index) => {
                            index = JSON.parse(index)
                            index.uploadedAt = new Date(index.uploadedAt)
                            $.get({
                                url: `https://api.themoviedb.org/3/movie/${index.tmdb}?api_key={{tmdb_apikey}}`,
                                success: (data) => {
                                    $.get({
                                        url: `https://api.themoviedb.org/3/movie/${index.tmdb}/keywords?api_key={{tmdb_apikey}}`,
                                        success: (keywords) => {
                                            $.get({
                                                url: `https://api.themoviedb.org/3/movie/${index.tmdb}/credits?api_key={{tmdb_apikey}}`,
                                                success: (actors) => {
                                                    document.title = `${title_prefix} - ${data.title}`
                                                    FileDetailsContainer.html(``);
                                                    try {
                                                        FileDetailsContainer.append(`{% include "parts/FilmView.html" %}`)
                                                    }
                                                    catch {}
                                                },
                                                error: (error) => {
                                                    alert(`Ran in to an issue fetching the tmdb credits data, create a GitHub issue!`)
                                                }
                                            })
                                        },
                                        error: (error) => {
                                            alert(`Ran in to an issue fetching the tmdb keyword data, create a GitHub issue!`)
                                        }
                                    })
                                },
                                error: (error) => {
                                    alert(`Ran in to an issue fetching the tmdb data, create a GitHub issue!`)
                                }
                            })
                        },
                        error: (error) => {
                            alert(`Ran in to an issue fetching the film json data, create a GitHub issue!`)
                        }
                    })
                    break;
                }
                case "album": {
                    $.get({
                        url: `${base_url}${url}`,
                        success: (index) => {
                            index = JSON.parse(index)
                            index.uploadedAt = new Date(index.uploadedAt)
                            $.get({
                                url: `{{ url_for('views.get_json') }}?url=${index.genius}`,
                                success: (data) => {
                                    data = data.response.page_data
                                    document.title = `${title_prefix} - ${data.album.full_title}`
                                    FileDetailsContainer.html(``);
                                    try {
                                        FileDetailsContainer.append(`{% include "parts/AlbumView.html" %}`)
                                    }
                                    catch {}
                                    $("[ReadMore]").click(() => {
                                        $("#ReadMoreOverview").toggle();
                                    })
                                },
                                error: (error) => {
                                    alert(`Ran into an issue fetching the genius details, create a GitHub issue!`);
                                }
                            })
                        },
                        error: (error) => {
                            alert(`Ran in to an issue fetching the album json data, create a GitHub issue!`)
                        }
                    }) 
                    break;
                }
                case "single":
                case "track": {
                    $.get({
                        url: `${base_url}${url}`,
                        success: (index) => {
                            index = JSON.parse(index)
                            $.get({
                                url: `{{ url_for('views.get_json') }}?url=${index.genius}`,
                                success: (data) => {
                                    data = data.response.song
                                    document.title = `${title_prefix} - ${data.full_title}`
                                    FileDetailsContainer.html(``);
                                    var favicon = $("#favicon")
                                    favicon.attr("href", data.header_image_url) 
                                    const album = location.search.split("&type=")[1].split("&album=")[1];
                                    try {
                                        FileDetailsContainer.append(`{% include "parts/TrackView.html" %}`)
                                    }
                                    catch {}
                                    $("[ReadMore]").click(() => {
                                        $("#ReadMoreOverview").toggle();
                                    })
                                },
                                error: (error) => {
                                    alert(`Ran into an issue fetching the genius details, create a GitHub issue!`);
                                }
                            })
                        },
                        error: (error) => {
                            alert(`Ran in to an issue fetching the album json data, create a GitHub issue!`)
                        }
                    }) 
                    break;
                }
            }
        </script>
    </div>
{% endblock %}

src/app/templates/parts/AlbumCard.html
<a href="{{ url_for('views.view') }}?url=${view_url}&type=${index.type}">
    <div class="bg-zinc-800 media-card rounded-lg group overflow-hidden max-w-[200px] shrink-0 flex-col flex w-full">
        <div class="overflow-hidden">
            <img loading="lazy" src="${data.album.cover_art_url}" alt="${data.album.full_title} Cover" class="group-hover:scale-110 transition-all">
        </div>
        <div class="flex text-sm items-center gap-2 p-2">
            <h1 class="truncate" title="${data.album.full_title}">${data.album.full_title}</h1>
            <span class="text-zinc-600">•</span>
            <p>${data.album.release_date.split("-")[0]}</p>
        </div>
    </div>
</a>

src/app/templates/parts/AlbumView.html
<div class="relative p-4 bg-zinc-700/20 overflow-hidden rounded-xl">
    <img loading="eager" src="${data.album.custom_header_image_url}" class="absolute z-[-10] brightness-[0.2] rounded-xl select-none sm:blur-sm w-full top-0 left-0 right-0 bottom-0">
    <div class="flex w-full gap-6 items-center sm:flex-row flex-col">
        <a href="${data.album.cover_art_url}" class="sm:w-3/12" target="_blank">
            <img loading="lazy" src="${data.album.cover_art_url}" class="overflow-hidden border border-white/5 rounded-lg" alt="${data.album.full_title} Cover">
        </a>
        <div class="flex sm:w-9/12 flex-col h-full">
            <div class="space-y-4">
                <div class="space-y-0.5">
                    <h1 class="text-3xl font-semibold">${data.album.name}</h1>
                    <h2 class="text-lg">${data.album.artist.name}</h2>
                    <p class="text-sm text-zinc-400 flex items-center gap-1">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="w-4 h-4 -mt-[1px]"><path d="M8 2v4"/><path d="M16 2v4"/><rect width="18" height="18" x="3" y="4" rx="2"/><path d="M3 10h18"/></svg>
                        Released ${data.album.release_date_for_display}
                    </p>
                </div>
                <div class="space-y-1.5">
                    <h2 class="text-lg">Overview</h2>
                    <div class="p-2 bg-zinc-700/30 backdrop-blur-sm rounded-lg">
                        ${data.album.description_preview ? `
                            <p ReadMore class="text-zinc-400 cursor-pointer text-sm clammped-text">${data.album.description_preview}</p>
                        `:`
                            <p class="text-zinc-400 cursor-pointer text-sm clammped-text">No overview provided</p>
                        `}
                    </div>
                    <style>
                        .clammped-text {
                            overflow: hidden;
                            display: -webkit-box;
                            -webkit-line-clamp: 3;
                                    line-clamp: 3; 
                            -webkit-box-orient: vertical;
                         }
                    </style>
                </div>
                <div class="flex justify-between items-start w-full">
                    <div class="text-xs text-left">
                        <p>Uploaded At: ${index.uploadedAt}</p>
                        <p>Uploaded By: '${index.uploadedBy}'</p>
                        <p>Available Tracks: ${index.tracks.length}</p>
                        <p>Filesize: ${filesize(index.size)}</p>
                    </div>
                    <div class="flex gap-2">
                        <button class="h-11 text-sm animate-pulse px-4 bg-zinc-700 rounded-full" title="Download '${data.album.full_title}' • ${index.type}">Download</button>
                        <div id="ReadMoreOverview" style="display: none;" class="absolute flex items-center justify-center top-0 left-0 right-0 bottom-0 p-4">
                            <div class="sm:w-4/6 flex h-fit max-h-[100%] bg-zinc-700/50 backdrop-blur-xl p-4 rounded-xl mx-auto">
                                <div class="space-y-2 flex flex-col">
                                    <div class="flex items-start justify-between">
                                        <div>
                                            <h1 class="text-2xl">Overview</h1>
                                            <p class="text-sm">${data.album.name_with_artist}</p>
                                        </div>
                                        <button ReadMore>
                                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="w-5 h-5"><path d="M18 6 6 18"/><path d="m6 6 12 12"/></svg>
                                        </button>
                                    </div>
                                    <p class="text-zinc-400 flex flex-col pr-2 overflow-y-auto">${data.album.description_preview}</p>
                                </div>
                            </div>
                        </div>
                        <button ReadMore class="h-11 flex items-center text-sm px-4 border-zinc-700 hover:bg-zinc-700 transition-all border rounded-full">More Details</button>
                        <a href="${data.album.url}" title="View '${data.album.full_title}' on Geniuis" target="_blank" class="h-11 w-11 text-sm bg-zinc-700 rounded-full flex items-center justify-center">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="w-4 h-4"><path d="M15 3h6v6"/><path d="M10 14 21 3"/><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/></svg>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="my-6 sm:px-0 px-4">
    <div class="flex sm:flex-row flex-col gap-6">
        <div class="sm:w-4/6 flex flex-col">
            <div class="space-y-2 flex flex-col">
                <h1 class="text-xl font-medium">Tracklist</h1>
                <div class="text-sm divide-y divide-zinc-700">
                    ${data.album_appearances.map((track) => {
                        const index_track = index.tracks.find((index_track) => index_track.id == track.track_number);
                        if (index_track) {
                            return `
                                <a href="{{ url_for('views.view') }}?url=/music/albums/tracks/${index_track.location}&type=track&album=${url}" class="flex items-start text-white p-1 gap-2">
                                    <p>${track.track_number}.</p>
                                    <h1>${track.song.title}</h1>
                                    ${track.song.featured_artists && track.song.featured_artists.length > 0 ? `
                                        <span>•</span>
                                        <p>${track.song.featured_artists.map(featured_artist => featured_artist.name).join('-')}</p>
                                    ` : ''}
                                </a>
                            `;
                        } else {
                            return `
                                <div class="flex select-none items-start text-zinc-600 cursor-default p-1 gap-2">
                                    <p>${track.track_number}.</p>
                                    <h1>${track.song.title}</h1>
                                    ${track.song.featured_artists && track.song.featured_artists.length > 0 ? `
                                        <span>•</span>
                                        <p>${track.song.featured_artists.map(featured_artist => featured_artist.name).join('-')}</p>
                                    ` : ''}
                                </div>
                            `;
                        }
                    }).join('')}
                </div>
            </div>
            
        </div>
        <div class="sm:w-2/6 flex flex-col gap-4">
            <div class="space-y-2">
                <h1 class="text-xl font-medium">Other Albums by ${data.album.artist.name}</h1>
                <div class="grid grid-cols-2 gap-4">
                    ${data.other_albums_by_artist.slice(0, 6).map((album) => `
                        <a href="${album.url}" target="_blank" class="bg-zinc-700 rounded-md group overflow-hidden">
                            <div class="overflow-hidden">
                                <img loading="lazy" src="${album.cover_art_url}" alt="${album.full_title} Cover" class="group-hover:scale-110 transition-all">
                            </div>
                            <div class="flex text-sm items-center gap-2 p-2">
                                <h1 class="truncate" title="${album.full_title}">${album.full_title}</h1>
                            </div>
                        </a>
                    `).join('')}
                </div>
            </div>
        </div>
    </div>
</div>

src/app/templates/parts/FilmCard.html
<a href="{{ url_for('views.view') }}?url=${view_url}&type=${index.type}">
    <div class="bg-zinc-800 media-card rounded-lg group overflow-hidden max-w-[200px] shrink-0 flex-col flex w-full">
        <div class="overflow-hidden">
            <img loading="lazy" src="https://image.tmdb.org/t/p/original/${data.poster_path}" alt="${data.original_title} Cover" class="group-hover:scale-110 transition-all">
        </div>
        <div class="flex text-sm items-center gap-2 p-2">
            <h1 class="truncate" title="${data.original_title}">${data.original_title}</h1>
            <span class="text-zinc-600">•</span>
            <p>${data.release_date.split("-")[0]}</p>
        </div>
    </div>
</a>

src/app/templates/parts/LatestAlbums.html
<div class="my-6 space-y-4">
    <h1 class="text-2xl font-semibold flex items-center gap-2">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-library"><path d="m16 6 4 14"/><path d="M12 6v14"/><path d="M8 8v12"/><path d="M4 4v16"/></svg>
        Latest Albums
    </h1>
    <div id="LatestAlbumsGrid" class="flex gap-6 overflow-x-auto mb-2">
        {% include "parts/LoadingSpinner.html" %}
    </div>
    <script>
        const LatestAlbumsGrid = $("#LatestAlbumsGrid");
        $.get({
            url: `https://raw.githubusercontent.com/MediahTM/Mediah-Downloads/main/downloads/music/albums/MAP.json`,
            success: (mapper) => {
                mapper = JSON.parse(mapper);
                for (let i = 0; i < 10 && i < mapper.length; i++) {
                    const item = mapper[i];
                    const url = `https://raw.githubusercontent.com/MediahTM/Mediah-Downloads/main/downloads/music/albums/${item}`;
                    const view_url = `/music/albums/${item}`;

                    $.get({
                        url: url,
                        success: (index) => {
                            index = JSON.parse(index)
                            LatestAlbumsGrid.html(``);
                            $.get({
                                url: `{{ url_for('views.get_json') }}?url=${index.genius}`,
                                success: (data) => {
                                    data = data.response.page_data
                                    LatestAlbumsGrid.append(`{% include "parts/AlbumCard.html" %}`)
                                },
                                error: (error) => {
                                    alert(`Ran into an issue fetching the genius details, create a GitHub issue!`);
                                }
                            })
                        },
                        error: (error) => {
                            alert(`Ran into an issue fetching the album details, create a GitHub issue!`);
                        }
                    })
                }
            },
            error: (error) => {
                alert(`Ran into an issue fetching the album mapper, create a GitHub issue!`);
            }
        });
    </script>
</div>

src/app/templates/parts/LatestSingles.html
<div class="my-6 space-y-4">
    <h1 class="text-2xl font-semibold flex items-center gap-2">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#ffffff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-disc-album"><rect width="18" height="18" x="3" y="3" rx="2"/><circle cx="12" cy="12" r="5"/><path d="M12 12h.01"/></svg>
        Latest Singles
    </h1>
    <div id="LatestSinglesGrid" class="flex gap-6 overflow-x-auto mb-2">
        {% include "parts/LoadingSpinner.html" %}
    </div>
    <script>
        const LatestSinglesGrid = $("#LatestSinglesGrid");

        $.get({
            url: "https://raw.githubusercontent.com/MediahTM/Mediah-Downloads/main/downloads/music/singles/MAP.json",
            success: (mapper) => {
                mapper = JSON.parse(mapper);
                for (let i = 0; i < 10 && i < mapper.length; i++) {
                    const item = mapper[i];
                    const url = `https://raw.githubusercontent.com/MediahTM/Mediah-Downloads/main/downloads/music/singles/${item}`;
                    const view_url = `/music/singles/${item}`;

                    $.get({
                        url: url,
                        success: (index) => {
                            index = JSON.parse(index)
                            LatestSinglesGrid.html(``);
                            $.get({
                                url: `{{ url_for('views.get_json') }}?url=${index.genius}`,
                                success: (data) => {
                                    data = data.response.song
                                    LatestSinglesGrid.append(`{% include "parts/TrackCard.html" %}`)
                                },
                                error: (error) => {
                                    alert(`Ran into an issue fetching the genius details, create a GitHub issue!`);
                                }
                            })
                        },
                        error: (error) => {
                            alert(`Ran into an issue fetching the single details, create a GitHub issue!`);
                        }
                    })
                }
            },
            error: (error) => {
                alert(`Ran into an issue fetching the singles mapper, create a GitHub issue!`);
            }
        })
    </script>
</div>

src/app/templates/parts/TrackCard.html
<a href="{{ url_for('views.view') }}?url=${view_url}&type=${index.type}">
    <div class="bg-zinc-800 media-card rounded-lg group overflow-hidden max-w-[200px] shrink-0 flex-col flex w-full">
        <div class="overflow-hidden">
            <img loading="lazy" src="${data.header_image_thumbnail_url}" alt="${data.song} Cover" class="group-hover:scale-110 transition-all">
        </div>
        <div class="flex truncate text-sm items-center gap-2 p-2">
            <h1 title="${data.title}">${data.title}</h1>
        </div>
    </div>
</a>

src/app/templates/view.html
{% extends "layout.html" %}

{% block content %}
    <div class="px-4">
        <div class="mx-auto container w-full">
            <div id="FileDetailsContainer">

            </div>
        </div>
        <script>
            const FileDetailsContainer = $("#FileDetailsContainer");
            const type = location.search.split("&type=")[1].toString();
            const endpoint = location.search.split("?url=")[1].split("&")[0].toString();

            console.log(`Endpoint: ${endpoint}`)
            console.log(`Type: ${type}`)

            FileDetailsContainer.html("");
            $.get({
                url: endpoint,
                success: (data) => {
                    data = JSON.parse(data);
                    data.uploadedAt = new Date(data.uploadedAt)
                    switch (type) {
                        case "film": {
                            FileDetailsContainer.append(`{% include "parts/MovieView.html" %}`)
                        }
                        case "album": {
                            let tracksHTML = ``;
                            let promises = [];

                            for (let i = 0; i < data.tracks.length; i++) {
                                let track = data.tracks[i];
                                const url = `https://raw.githubusercontent.com/MediahTM/Mediah-Downloads/main/downloads/music/albums/tracks/${track}`;
                                let promise = $.get({
                                    url: url,
                                    success: (xhr) => {
                                        xhr = JSON.parse(xhr);
                                        tracksHTML += `<a href="{{ url_for('views.view') }}?url=${url}&type=track">${i + 1}. ${xhr.name} <span class="text-zinc-600">•</span> ${xhr.playtime}</a>`;
                                        console.log(`${i + 1}. ${xhr.name}`);
                                        console.log(tracksHTML);
                                    }
                                });
                                promises.push(promise);
                            }

                            $.when.apply($, promises).done(() => {
                                console.log(tracksHTML);
                                FileDetailsContainer.append(`{% include "parts/AlbumView.html" %}`);
                            });

                            break; 
                        }
                        case "track": {
                            FileDetailsContainer.append(`{% include "parts/TrackView.html" %}`);
                        }
                    }
                },
                error: (data) => {
                    window.location = "{{ url_for('views.index') }}"
                } 
            })
        </script>
    </div>
{% endblock %}